#define IMG_TARGET_NORMAL_BLUE 6
#define IMG_TARGET_NORMAL_GREEN 7
#define IMG_TARGET_NORMAL_YELLOW 8
#define IMG_TARGET_NORMAL_RED 9

#define IMG_TARGET_MINI_BLUE 10
#define IMG_TARGET_MINI_GREEN 11
#define IMG_TARGET_MINI_YELLOW 12
#define IMG_TARGET_MINI_RED 13

#define IMG_TARGET_BIG_BLUE 14
#define IMG_TARGET_BIG_GREEN 15
#define IMG_TARGET_BIG_YELLOW 16
#define IMG_TARGET_BIG_RED 17

#define IMG_BLOCK_NORMAL 18
#define IMG_BLOCK_MINI 19
#define IMG_BLOCK_BIG 20

#define IMG_BLOCK_ORANGE 21

#define IMG_LINE1 22
#define IMG_LINE2_A 23
#define IMG_LINE2_B 24
#define IMG_LINE3 25
#define IMG_LINE4 26
#define IMG_LINE5 27
#define IMG_LINE6_A 28
#define IMG_LINE6_B 29
#define IMG_LINE7 30
#define IMG_LINE8 31
#define IMG_LINE9 32
#define IMG_LINE10 33

#define IMG_SWITCH_ORANGE 34
#define IMG_SWITCH_ORANGE_HIT 35

